services:
  - type: web
    name: sheron-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.server:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JAMENDO_CLIENT_ID
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SERVER_SECRET
        sync: false
